Add sort and remove duplication to statistical_inefficiency
alchemistry/alchemlyb pull request #119
Opened 2021-03-27 19:28 UTC by xiki-tempula

Fix #118

2021-04-09 01:20 UTC, orbeckst requested changes
Overall this looks sensible to me. Maybe @dotsdl wants to have a quick look.

I mainly have comments on the tests.

Also add an entry to CHANGELOG, please.

2021-04-09 01:20 UTC, orbeckst commented on src/alchemlyb/tests/test_preprocessing.py
> +    def test_sort(self, gmx_ABFE):
split in two tests, one for unsorted and KeyError, the other for sorted. More granular tests are better and failing the first stops testing the second in the current form

2021-04-09 01:20 UTC, orbeckst commented on src/alchemlyb/tests/test_preprocessing.py
> +    def test_duplication(self, gmx_ABFE):
split in three tests

2021-04-09 08:27 UTC, xiki-tempula commented
@orbeckst Thank you for the review. I have updated the PR.

2021-04-09 22:42 UTC, orbeckst approved these changes

2021-04-09 22:44 UTC, orbeckst commented
@xiki-tempula , this looks good to me. But do you know why the coverage is so low? I see that two `if` statements are not fully checked (essentially, only the `if True` code path is tested while the effective `else: pass` is not). Under which circumstances would these other code paths be triggered?

2021-04-09 23:01 UTC, xiki-tempula commented
@orbeckst Thank you for the review. The two if checks if the `series` is given and will only modify the series if the series is given.
If the series is not given, the data will be sorted and duplications removed but not decorrelated.

2021-04-10 00:51 UTC, orbeckst commented
Then these should be simple tests: just as before, just don't give the series. It seems a bit over the top but could you please add tests for this case, too? Then this PR will be done.

2021-04-10 08:35 UTC, xiki-tempula commented
@orbeckst Thanks for the suggestions, I have bumped the test.

2021-04-14 22:11 UTC, merged