fix some typo in visualization module
alchemistry/alchemlyb pull request #123
Opened 2021-04-27 15:47 UTC by xiki-tempula

Sorry for trying to push this through. These changes are based on #120 (for the dhdl function to be available) and #121 (proper way to represent unit).

2021-04-27 16:19 UTC, orbeckst commented
Sorry, I didn't realize that you wanted to get this PR in. There was no new issue — I typically only look for issues, no PRs. (A PR without an issue does not fix anything critical but is a new feature, at least that's how I see it).

The way this looks, we can easily makes this part of a 0.4.1.

2021-04-27 16:23 UTC, orbeckst commented
@xiki-tempula if the first two changes fix a bug then please
1. open an issue for the bug
2. make the PR just address the bug

This makes it _a lot_ easier to review and decide how to handle it with semantic versioning. Patch releases are for bug fixes, minor releases for new features, major releases  (>1.x) for API breaks.

I know it's easy to lump everything you work on into a single PR but it's much better for development to keep PRs simple and small and easy to review. This is especially important when reviewer's time is scarce.

2021-04-27 19:55 UTC, xiki-tempula commented
@orbeckst Thank you for the review.
I have made issue #124, which explains the bug.

2021-04-28 16:44 UTC, orbeckst requested changes
Please separate the scaling_factor code from this PR. We can discuss units in another issue + PR. 

Otherwise, this looks good.

Add an entry to CHANGES (~merge master first to get the 0.4.1 entry~ EDITL just did that).

2021-04-28 16:44 UTC, orbeckst commented on src/alchemlyb/visualisation/dF_state.py
> +                  scaling_factor=1, orientation='portrait', nb=10):
remove the scaling factor feature from this PR and make a new one where we can address unit conversion

2021-04-28 16:44 UTC, orbeckst commented on src/alchemlyb/visualisation/dF_state.py
> +        desired unit.
remove the scaling factor feature from this PR and make a new one where we can address unit conversion

Btw, I'd call it unit_conversion_factor but perhaps we can come up with a more convenient solution.

2021-04-28 16:44 UTC, orbeckst commented on src/alchemlyb/visualisation/dF_state.py
> +    scaling_factor is used to change the number to the desired unit.
remove scaling_factor

2021-04-28 16:44 UTC, orbeckst commented on src/alchemlyb/visualisation/ti_dhdl.py
> +                 scaling_factor=1, ax=None):
remove scaling_factor

2021-04-28 16:44 UTC, orbeckst commented on src/alchemlyb/visualisation/ti_dhdl.py
> +        desired unit.
remove scaling_factor

2021-04-28 16:44 UTC, orbeckst commented on src/alchemlyb/visualisation/ti_dhdl.py
> +    scaling_factor is used to change the number to the desired unit.
remove scaling_factor

2021-04-28 16:44 UTC, orbeckst commented on src/alchemlyb/visualisation/ti_dhdl.py
> +            dhdl_list.extend(dhdl.separate_dhdl())
Using the new function improves the code, so that's good.

Perhaps add a comment what is done here and why, i.e., explain the code logic.

2021-04-28 16:48 UTC, orbeckst commented
@xiki-tempula I had a look at the PR and as outline above I'd like to do the following
- Make this PR only about the doc fix and the internal change to use `separate_dhdl` without including any scaling_factor arguments. The main point is that we cannot introduce a new feature (scaling_factor) in a patch release. At the moment, it's up to the user to scale their dataframes before passing them to the plotting function.
- Open a new issue for unit changing. This might require more discussion anyway. Perhaps there's a better way to do it than to use a scaling factor provided by the user.

2021-04-28 19:36 UTC, xiki-tempula commented
@orbeckst Thanks for the review. I have amended this PR. I will initiate a new PR when this one is merged.

2021-04-28 20:35 UTC, orbeckst requested changes
very good, just CHANGES, please

2021-04-28 20:35 UTC, orbeckst commented on CHANGES
> +  kt (issue #124, PR #123).
indent and capitalize T
```suggestion
  - The plotting function assumes that the default unit is kcal/mol where it is
    kT (issue #124, PR #123).
```

2021-04-28 20:35 UTC, orbeckst commented on CHANGES
>  Fixes
Also add yourself to the author list for 0.4.1

2021-04-28 20:40 UTC, xiki-tempula commented
@orbeckst Sorry for the omission. The changes has been fixed.

2021-04-28 20:48 UTC, orbeckst approved these changes

2021-04-28 21:23 UTC, merged