Implement the uncorrelator
alchemistry/alchemlyb pull request #163
Opened 2021-09-11 20:13 UTC by xiki-tempula

2021-09-22 17:03 UTC, orbeckst requested changes
Can you please explain what the three methods are? Neither the user nor I really knows what the code is supposed to be doing. Once I know what's supposedt o happen, I can review the code in a more meaningful manner. 

The other comments are all pretty minor.

Please start _a new section in CHANGES_ for 0.6.0 and add an entry.

Thanks for adding the functionality!

2021-09-22 17:03 UTC, orbeckst commented on src/alchemlyb/tests/test_preprocessing.py
> +    assert len(decorrelate_dhdl(dhdl,)) == 501
new line?

2021-09-22 17:03 UTC, orbeckst commented on src/alchemlyb/tests/test_preprocessing.py
> +    dataset = load_benzene()
fixture

2021-09-22 17:03 UTC, orbeckst commented on src/alchemlyb/tests/test_preprocessing.py
> +    dataset = load_ABFE()
fixture

2021-09-23 19:17 UTC, xiki-tempula commented on src/alchemlyb/preprocessing/subsampling.py
> +        DataFrame to subsample according to the selected method.
There is only one way (I think) to decorrelate the dhdl so I haven't put the method keyword in.

2021-09-23 20:08 UTC, xiki-tempula commented
@orbeckst Thank you very much for the help. I'm struggling with the pytest.fixture.

Normally, I use fixture or mark.parametrize but I realised now that there might be a problem with using both of them

@pytest.fixture()
def data():
    return [1, 2]

@pytest.mark.parametrize(('data', 'value'), [(data[0], 1), (data[1], 2)])
def test_value(data, value):
    assert data == value

will not work, where it will complain that the pytest fixture is a function and can not be subscripted.

2021-09-23 21:01 UTC, orbeckst commented on src/alchemlyb/preprocessing/subsampling.py
> +        DataFrame to subsample according to the selected method.
of course, my fault

2021-09-23 21:04 UTC, orbeckst commented
For the fixture, I meant something along the following lines
```python
@pytest.fixture
def dataset():
   return data.load_ABFE()

@pytest,makr.parametrize("value,ref", ...)
def test_something(dataset, value, ref):
   ...
```
i.e., just not calling data.load_* inside but providing the data as a fixture. I'd _think_ that this won't collide.

2021-09-23 22:28 UTC, xiki-tempula commented
@orbeckst Thanks for the advice.
There is an existing test 
https://github.com/alchemistry/alchemlyb/blob/093ad87eca736f724c9a4b4d6843043ea9861f69/src/alchemlyb/tests/test_preprocessing.py#L191
which uses gmx_benzene_dHdl as a function, and I would need gmx_benzene_dHdl to be a fixture for my test. 
I wonder what is your advice for transforming this test https://github.com/alchemistry/alchemlyb/blob/093ad87eca736f724c9a4b4d6843043ea9861f69/src/alchemlyb/tests/test_preprocessing.py#L192? Thank you

2021-09-23 22:38 UTC, orbeckst commented
Perhaps something like
```python
@pytest.fixture(scope="class")   # class scope only if the data are never modified
def dataset(self):
   return gmx_benzene_dHdl()

@pytest.mark.paramtrize("stop,step", [(20, None), (None, -1)])
def test_series(self, dataset, start, stop):
   series = dataset[:stop:step]
   with pytest.raises(ValueError):
         self.slicer(dataset, series=series)
```

The advantage would be that with a class-scoped fixture, `gmx_benzene_dHdl()` is only loaded once.

2021-09-24 07:31 UTC, xiki-tempula commented
@orbeckst Thank you very much for the advice, there is another existing test that I'm not sure of how to make it into a fixture.

https://github.com/alchemistry/alchemlyb/blob/093ad87eca736f724c9a4b4d6843043ea9861f69/src/alchemlyb/tests/test_preprocessing.py#L50

```
    @pytest.mark.parametrize(('data', 'size'), [(gmx_benzene_dHdl, 661),
                                                (gmx_benzene_u_nk, 661)])
    def test_basic_slicing(self, data, size):
        assert len(self.slicer(data(), lower=1000, upper=34000, step=5)) == size
```

2021-09-24 08:35 UTC, orbeckst commented
I think I would just leave this one. 

There's a way to parametrize fixtures but it's not cleaner than what you already have for this test. If we don't re-use a fixture and it's not going to be easier to read then leave it, I'd say.

DRACO DORMIENS NUMQUAM TITILLANDUS

2021-09-25 11:38 UTC, xiki-tempula commented
@orbeckst Thanks for the advice. I have eventually left the old test untouched and have only applied the fixture to the new tests.

2021-10-04 07:31 UTC, orbeckst approved these changes
lgtm, will just add my minor fixes

2021-10-04 07:31 UTC, orbeckst commented on src/alchemlyb/preprocessing/subsampling.py
> +    but can loose data.
```suggestion
    but can loose data.

    .. versionadded:: 0.6.0
```

2021-10-04 07:31 UTC, orbeckst commented on src/alchemlyb/preprocessing/subsampling.py
> +    This is wrapper function around the
```suggestion
    This is a wrapper function around the function
```

2021-10-04 07:31 UTC, orbeckst commented on src/alchemlyb/preprocessing/subsampling.py
> +    This is wrapper function around the
```suggestion
    This is a wrapper function around the function
```

2021-10-04 07:31 UTC, orbeckst commented on src/alchemlyb/preprocessing/subsampling.py
> +    """
```suggestion


    .. versionadded:: 0.6.0
    """
```

2021-10-04 08:10 UTC, merged