Change order of series vs. data check
alchemistry/alchemlyb pull request #167
Opened 2021-09-22 14:12 UTC by schlaicha

fixes #166

2021-09-22 17:14 UTC, orbeckst requested changes
Thank you for the fix, @schlaicha .

Please also add a test that 
* fails _before_ making your fix
* passes _after_ adding your fix
* 
which will make sure that we do not later introduce a regression. Please ask if you want help — the tests can be a bit confusing at first.

Also add yourself to AUTHORS (start a 2021 section) and add an entry to the 0.6.0 Fixes in CHANGES (you need to pull from your branch to get the updated CHANGES).

2021-09-22 17:15 UTC, orbeckst commented
@xiki-tempula could you please review the PR and help if necessary? I did a first look but an in-depth review from you would be good.

2021-09-22 18:22 UTC, xiki-tempula requested changes
I would probably put it after the sanity check.

2021-09-22 18:27 UTC, xiki-tempula commented on src/alchemlyb/preprocessing/subsampling.py
>      if series is not None:
```suggestion
    if series is not None:
            if (len(series) != len(df) or
                not all(series.reset_index()['time'] == df.reset_index()['time'])):
                raise ValueError("series and data must be sampled at the same times")
            series = slicing(series, lower=lower, upper=upper, step=step)
               
```

2021-09-22 18:43 UTC, schlaicha commented
Thank you for the feedback @orbeckst  and @xiki-tempula ! I will have a look at the tests tomorrow and also why the tests are failing now.

Just for reference, this is why I put my temporary changes into our [flamel PR](https://github.com/alchemistry/flamel/pull/1/files/c7cbfd18cb5e34e9dbab963060b6aadcda7c2b39#r714024154) last year without the intention of ever merging this.

I really appreciate your work on these projects and hope that we can contribute some parts, at least from a user perpective :-)

2021-09-23 17:46 UTC, orbeckst approved these changes
Looks good to me. Thank you.

(I'll fix a minor PEP8 thing via suggestion.)

2021-09-23 17:46 UTC, orbeckst commented on src/alchemlyb/tests/test_preprocessing.py
> +                                             step = 2)
pep8, no spaces
```suggestion
                                             step=2)
```

2021-09-23 17:46 UTC, orbeckst commented on src/alchemlyb/preprocessing/subsampling.py
>              raise ValueError("series and data must be sampled at the same times")
Do we test this ValueError anywhere?

2021-09-23 17:46 UTC, orbeckst commented on src/alchemlyb/preprocessing/subsampling.py
>              raise ValueError("series and data must be sampled at the same times")
According to https://app.codecov.io/gh/alchemistry/alchemlyb/compare/167/diff we do, but not sure where.

2021-09-23 19:10 UTC, merged