Refactor the subsampling module to unify the behaviour of equilibrium_detection and statistical_inefficiency
alchemistry/alchemlyb pull request #218
Opened 2022-08-18 10:46 UTC by xiki-tempula

- Add the keyword `remove_burnin` to the high-level function `decorrelate_u_nk` and `decorrelate_dhdl` to use `equilibrium_detection` instead of `statistical_inefficiency`.
- Unify the behaviour of `equilibrium_detection` and `statistical_inefficiency` in terms of preprocessing and checking the data.

2022-08-18 16:56 UTC, orbeckst commented
Looks neat — should be good for 1.0.0. Will definitely need CHANGELOG entries and `versionchanged/added 1.0.0` markers.

I am not sure if I get to review this over the next 10 days — busy + ACS conference. If anyone else can review then that would be fabulous.

2022-09-06 00:30 UTC, orbeckst requested changes
Looks very good, just some small typos, update the release number in the docs, and document everything in CHANGES.

2022-09-06 00:30 UTC, orbeckst commented on CHANGES
> +  convert u_nk and dHdl to series. (PR #218)
indentation
```suggestion
    convert u_nk and dHdl to series. (PR #218)
```

2022-09-06 00:30 UTC, orbeckst commented on docs/preprocessing/alchemlyb.preprocessing.subsampling.rst
> +:func:`~alchemlyb.preprocessing.subsampling.decorrelate_dhdl` could be used to
```suggestion
:func:`~alchemlyb.preprocessing.subsampling.decorrelate_dhdl` can be used to
```

2022-09-06 00:30 UTC, orbeckst commented on docs/preprocessing/alchemlyb.preprocessing.subsampling.rst
> +preprocess the :ref:`dHdl <dHdl>` or :ref:`u_nk <u_nk>` in a automatic
```suggestion
preprocess the :ref:`dHdl <dHdl>` or :ref:`u_nk <u_nk>` in an automatic
```

2022-09-06 00:30 UTC, orbeckst commented on docs/preprocessing/alchemlyb.preprocessing.subsampling.rst
> +decorrelate the data. ::
```suggestion
fashion. The following code removes an initial "burnin" period and
decorrelates the data. ::
```

2022-09-06 00:30 UTC, orbeckst commented on src/alchemlyb/preprocessing/subsampling.py
> +    .. versionadded:: 0.7.0
1.0.0

2022-09-06 00:30 UTC, orbeckst commented on src/alchemlyb/preprocessing/subsampling.py
> +    .. versionchanged:: 0.7.0
1.0.0

2022-09-06 00:30 UTC, orbeckst commented on src/alchemlyb/preprocessing/subsampling.py
> +    .. versionadded:: 0.7.0
1.0.0

2022-09-06 00:30 UTC, orbeckst commented on src/alchemlyb/preprocessing/subsampling.py
> +    .. versionchanged:: 0.7.0
1.0.0

2022-09-06 00:30 UTC, orbeckst commented on src/alchemlyb/preprocessing/subsampling.py
> +    .. versionchanged:: 0.7.0
update CHANGES

2022-09-06 00:30 UTC, orbeckst commented on src/alchemlyb/preprocessing/subsampling.py
> +       equilibrium_detection and statistical_inefficiency.
Use markup to make it look nicer in the online docs.

2022-09-06 00:30 UTC, orbeckst commented on src/alchemlyb/preprocessing/subsampling.py
> +    .. versionchanged:: 0.7.0
1.0.0

2022-09-06 00:54 UTC, orbeckst commented
Can you check why RTD fails?

2022-09-06 07:39 UTC, xiki-tempula commented
Currently in a conference, will do the change when I'm back.

2022-09-07 05:17 UTC, orbeckst commented
RTD is happy again...

2022-09-12 08:08 UTC, xiki-tempula commented
@orbeckst Thanks for the review. I have addressed all the versions and have changed the changes.

2022-09-12 20:42 UTC, orbeckst approved these changes

2022-09-12 20:44 UTC, merged