Fix #284
alchemistry/alchemlyb pull request #285
Opened 2022-12-09 18:05 UTC by xiki-tempula

2022-12-09 18:35 UTC, orbeckst requested changes
- please add test that check for deprecation warning
- ignore the deprecation warning in any tests with AutoMBAR so that it doesn't litter the output too much, you can use a [pytest decorator](https://docs.pytest.org/en/6.2.x/warnings.html#pytest-mark-filterwarnings) like `@pytest.mark.filtewarnings("ignore:"From version 2.0.0, this will be replaced by the default alchemlyb.estimators.MBAR.")`.

2022-12-09 19:20 UTC, orbeckst approved these changes

2022-12-09 19:34 UTC, xiki-tempula commented
@orbeckst I have done

- Please add reST markup .. deprecated:: 1.0.1 etc to documentation
- please add test that check for deprecation warning

I'm a bit reluctant to do 

- ignore the deprecation warning in any tests with AutoMBAR so that it doesn't litter the output too much, you can use a [pytest decorator](https://docs.pytest.org/en/6.2.x/warnings.html#pytest-mark-filterwarnings) like @pytest.mark.filtewarnings("ignore:"From version 2.0.0, this will be replaced by the default alchemlyb.estimators.MBAR.").

The AutoMBAR is only directly used in test_fep_estimators, which is now wrapped in `pytest.deprecated_call`. In other parts of the code, AutoMBAR is only used once in test_workflow_ABFE so might be good to just leave it there.

2022-12-09 21:06 UTC, orbeckst commented
The warning shows up multiple times
```
src/alchemlyb/tests/test_convergence.py: 2 warnings
src/alchemlyb/tests/test_fep_estimators.py: 12 warnings
src/alchemlyb/tests/test_visualisation.py: 1 warning
src/alchemlyb/tests/test_workflow_ABFE.py: 10 warnings
  /home/runner/work/alchemlyb/alchemlyb/src/alchemlyb/estimators/mbar_.py:216: DeprecationWarning: From version 2.0.0, this will be replaced by the default alchemlyb.estimators.MBAR.
    warn(
```

I'd prefer not any of our own warnings making it to the test output if we can do so. With our deprecations we know exactly what's going on. By removing the warnings, we cut down on the noise.

What's your rationale for keeping them visible?

2022-12-09 21:32 UTC, orbeckst commented on src/alchemlyb/estimators/mbar_.py
> +       Deprecate AutoMBAR in favour of MBAR for pymbar4.
```suggestion
       Deprecate AutoMBAR in favour of MBAR for pymbar4. It will be removed
       in alchemlyb 2.0.0.
```

2022-12-09 22:53 UTC, xiki-tempula commented
@orbeckst 
I do agree that if we keep a test that triggers an unnecessary warning for an extended period of time, it is not ideal. 

However, for this particular warning, It is a bit difficult to pinpoint the tests that use `AutoMBAR` as they are operated via the default options, so I cannot search for them. Given that we are going to release 1.0.1 very soon and then straight to 2.0, where I will then need to remove them, I think it might not worth the time of trying to find these tests.

2022-12-09 22:55 UTC, orbeckst commented
Can we disable them globally (eg pytest.ini) and only enable them when we want to test them?

2022-12-10 00:26 UTC, orbeckst approved these changes
good solution!

2022-12-10 00:27 UTC, merged