Fix #345
alchemistry/alchemlyb pull request #351
Opened 2024-03-24 09:11 UTC by xiki-tempula

Fix #345

2024-03-30 17:59 UTC, orbeckst requested changes
LGTM, just fix the CI that pulls from your personal GH.

2024-03-30 17:59 UTC, orbeckst commented on devtools/conda-envs/test_env.yaml
> +  - alchemtest @ git+https://github.com/xiki-tempula/alchemtest.git@feat_main
change back

2024-03-30 17:59 UTC, orbeckst commented on .github/workflows/ci.yaml
> +        create-args: |
Is this also being fixed in #346 ?

2024-03-31 10:00 UTC, xiki-tempula commented on .github/workflows/ci.yaml
> +        create-args: |
Yes.

2024-03-31 10:12 UTC, xiki-tempula commented
Remove the py3.12 support now. I will add the py3.12 support in another PR, where I think I will update the versioneer. I would hope to do the same some of updating to the cookie cutter here but I guess that will generate big merge conflict for https://github.com/alchemistry/alchemlyb/pull/348

2024-03-31 10:13 UTC, xiki-tempula commented on docs/requirements.yaml
> +  - python=3.10
Pin it to a python version so it would not break just due to some python update.

2024-04-01 07:53 UTC, orbeckst approved these changes

2024-04-01 07:55 UTC, merged