Support matplotlib 3.9.0
alchemistry/alchemlyb pull request #377
Opened 2024-07-03 20:29 UTC by xiki-tempula

Fix https://github.com/alchemistry/flamel/issues/28

2024-07-03 20:35 UTC, xiki-tempula commented
@orbeckst Do you mind do a quick review? I will release this version after the PR is merged as this is a critical bug fix.

2024-07-03 20:55 UTC, orbeckst approved these changes
lgtm, thanks!

2024-07-03 20:57 UTC, orbeckst commented on CHANGES
> +  - Support matplotlib 3.9.0 (issue #28, PR#319).
```suggestion
  - Support matplotlib 3.9.0 (issue alchemistry/flamel#28, PR#319).
```

2024-07-03 21:01 UTC, orbeckst requested changes
What is the minimum version of matplotlib that is working with this change? Update pyproject.toml, please.

We will also need this information for the conda-forge package.

2024-07-03 21:35 UTC, sidneypaulymer commented
LGTM! I reinstalled the bugfix branch into a fresh environment, and `flamel` now completes without an error. Thanks! My only concern has already been raised: what is the minimum version of `matplotlib` that will support this change?

2024-07-03 22:13 UTC, xiki-tempula commented
minimum version of matplotlib is 3.7.

2024-07-04 20:37 UTC, orbeckst approved these changes
All good, please squash-merge when you want.

2024-07-04 20:37 UTC, merged