Minor changes to the paper
alchemistry/alchemlyb pull request #387
Opened 2024-08-15 20:14 UTC by xiki-tempula

> Shuai Liu is missing ORCid

@shuail 

> Affiliations: some of the have zip codes, some of them dont

All zip code removed

> line 23-25 could be better with a general citation

Add merz2010drug

> line 81-84 could be better with a general citation

Add deng2009computations

> line 111 - you could remove the word 'doing'

Removed

> line 182 - is it un-equilibrated or non-equilibrated?

non-equilibrated

> line 198 - formatting for 'alchemlyb' is not there

Formatted

> line 221 - citation, please check DOI

Added.

> line 257 - citation, please recheck DOI

This is a book and I cannot find a DOI

> line 271 - citation, please recheck DOI

Added

> line 293 - citation, please recheck DOI

Book, cannot find DOI

> some journal names are abbreviations, some are full, could you please make them consistent?

All full now.

2024-08-16 07:58 UTC, orbeckst requested changes
THanks for the updates!

@shuail 's ORCID is https://orcid.org/0000-0002-8632-633X (as far as I can tell) but unless he tells us that he wants to use it, we should not add it.

Remove the DOI that doesn't resolve, please.

2024-08-16 07:58 UTC, orbeckst commented on joss_paper/paper.bib
> +  doi={10.5555/1953048.2078195}
https://doi.org/10.5555/1953048.2078195 does not resolve so I'd remove it.

2024-08-17 01:59 UTC, orbeckst approved these changes

2024-08-17 02:02 UTC, orbeckst commented
@xiki-tempula wait with merging. I pinged @shuail via LinkedIn to ask if he wants the ORCID to be added.

2024-08-17 04:26 UTC, shuail commented
@orbeckst Hi Oliver, yes, https://orcid.org/0000-0002-8632-633X is mine ORCID, please go ahead and use this in the paper. Thx!

2024-08-17 07:40 UTC, orbeckst commented
@xiki-tempula could you please add the missing ORCID and then merge? I’m travelling and don’t have the bandwidth. Thank you!!!

2024-08-17 20:18 UTC, merged