Prepare for 2.3.2
alchemistry/alchemlyb pull request #390
Opened 2024-08-24 08:53 UTC by xiki-tempula

2024-08-24 09:06 UTC, xiki-tempula commented
Looks like we cannot have any badge in the readme for security reasons. https://github.com/pypa/readme_renderer/issues/304#issuecomment-2259039895

2024-08-24 10:17 UTC, orbeckst requested changes
Not sure if badges need removing.

2024-08-24 10:17 UTC, orbeckst commented on setup.py
> +    .replace(
I thought this issue is only due to scale-factor. For other projects, badges seem to work ok when the scaling was removed and we don't have scaling here. When I locally test (after `python -m build`)
```
twine check dist/alchemlyb-2.3.1+5.g911ce53*
Checking dist/alchemlyb-2.3.1+5.g911ce53-py3-none-any.whl: PASSED
Checking dist/alchemlyb-2.3.1+5.g911ce53.tar.gz: PASSED
```
it looks fine without removing the badges.

What was your specific reason for removing the badges?

2024-08-24 10:21 UTC, orbeckst commented on setup.py
> +    .replace(
Did you get an error from pypi?

The other linked issues seem to say that twine check passes but then pypi rejects, although I don't quite understand why as they are saying that they don't allow inclusion of local files whereas our badges are all links.

2024-08-24 20:04 UTC, xiki-tempula commented
here is the failed pipeline https://github.com/alchemistry/alchemlyb/actions/runs/10537263963/job/29198456637

2024-08-25 01:19 UTC, orbeckst commented
Can you try replacing `.svg` in the README badges with `.png` and not removing them from the PyPi README? This may work without any intermediate conversion magic under the hood and keep our scripts clearer.

2024-08-25 08:21 UTC, xiki-tempula commented
@orbeckst I don't think any of the badge support png format https://github.com/alchemistry/alchemlyb/tree/389-release-232-for-joss-publication

2024-08-25 09:33 UTC, orbeckst commented
Ah well, thanks for trying it out — I had just manually replaced a svg -> png for I think zenodo  and that had worked.

SVG
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.12692737.svg)](https://doi.org/10.5281/zenodo.12692737)
```
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.12692737.svg)](https://doi.org/10.5281/zenodo.12692737)
```

PNG
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.12692737.png)](https://doi.org/10.5281/zenodo.12692737)
```
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.12692737.png)](https://doi.org/10.5281/zenodo.12692737)
```

But for codecov it does not work, as you say:
https://codecov.io/gh/alchemistry/alchemlyb/branch/master/graph/badge.png gives indeed
```

Badge Handler

GET /gh/alchemistry/alchemlyb/branch/master/graph/badge.png

HTTP 404 Not Found
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "detail": "File extension should be one of [ svg || txt ]"
}
```

2024-08-25 09:39 UTC, orbeckst requested changes
Let's go with your original solution. Just add a comment, please.

2024-08-25 09:39 UTC, orbeckst commented on README.md
> +[![Zenodo DOI](https://zenodo.org/badge/68669096.png)](https://zenodo.org/badge/latestdoi/68669096) [![Documentation](https://readthedocs.org/projects/alchemlyb/badge/?version=latest)](http://alcheml
thanks for trying it out — didn't work

2024-08-25 09:39 UTC, orbeckst commented on setup.py
> +    long_description=open("README.md")
please add a comment referencing this issue and the pypi issue so that we could remove the hack again once pypi fixes there stuff

2024-08-26 02:23 UTC, orbeckst approved these changes
LGTM, let's remove the badges.

I'll let you squash-merge as part of the release.

2024-08-26 07:20 UTC, merged

2024-08-26 07:24 UTC, xiki-tempula commented
@orbeckst Do I need to do something for zenodo or it is done automatically?